### ISSUE TITLE
Build should not continue for empty blocks

### ISSUE THREAD

**Issue by taylortom** [adapt-security/adapt-authoring-ui#159]
It's currently possible to run a preview of a course with empty blocks. Previously this caused an error popup and abortion of the build.

**Comment by taylortom** [comment]
Fixed

**Comment by joe-allen-89** [comment]
With an empty block and clicking preview I'm still getting through to a loading screen, errors logged in console for empty block.

**Comment by taylortom** [comment]
Have just updated the server, and this is working for me now, apologies!

**Comment by joe-allen-89** [comment]
Update has done the trick nicely. Working as expected.
