### ISSUE TITLE
Entering a new tag clears the tags field.

### ISSUE THREAD

**Issue by memeteli** [adapt-security/adapt-authoring-ui#168]
At "Add Course" page, after selecting some tags from tags suggestion, I tried to enter a new tag, but it clears the tags field and removes already selected tags.

![image](https://user-images.githubusercontent.com/54360982/149939218-5f7a2645-1d9d-45d1-bdce-faa554d6183a.png)

**Comment by taylortom** [comment]
Fixed

**Comment by fkcailiniyazi** [comment]
I still have the same problem.

Steps for reproduce: 
1. Create new course
2. At Tags section, select some tags and type some words

**Comment by joe-allen-89** [comment]
Still getting the error as amaimaiti describes. 

Whilst creating a new course, add suggested tags then try to add a new tag, when pressing enter it clears all of them. However, after they all clear, if you repeat the same steps of adding suggested tags then typing one in, they then work.

Error appearing in the console every time a tag is added: 
"Uncaught (in promise) TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))"
