### ISSUE TITLE
Unable to add an asset to the graphic component

### ISSUE THREAD

**Issue by Christine-Yates** [adapt-security/adapt-authoring-ui#68]
I've tried using an existing asset and uploading a new asset. When selecting the asset, I'm receiving the error message 'An error occurred doing the save'.

**Comment by taylortom** [comment]
This should be fixed now

**Comment by Christine-Yates** [comment]
I'm still receiving the error when selecting an asset for the graphic component.
